### ISSUE TITLE
question about breakpoints

### ISSUE THREAD

**Issue by nihilee** [WeiWei060512/NUMTs-detection#1]
Dear author, I am confused about the large length between breakpoints of NUMTs when I read the paper and code, because searchNumtCluster_fromDiscordantReads.py and searchBreakpoint_fromblatoutputs.py should only output breakpoints within 1000bp? but actually many breakpoints in the paper Supplementary Tables with large distance even different chrom... Could you tell me where these breakpoints come from?

**Comment by WeiWei060512** [comment]
Hi, thanks for your interest of our work. We used 1000bp to cluster different NUMTs. We didn't set up any distance between two breakpoints.

Wei

**Comment by zqlns** [comment]
Dear author, I have been reading your code carefully recently. I am very confused with the following questions about searchBreakpoint_fromblatoutputs.py. Could you tell me why? Thank you for your time.
1. Why subtract 10 instead of other numbers in "df1 = df_input[(df_input['matchLEN'] < (readLEN - 10)) & (df_input['misMatch'] <= mismatchLEN)]"
2. What is the purpose of filtering out df2? I output df1 and df2 respectively, and there is no difference.
3. And what is the meaning of mtLeft in the column of "group" like "df_mtLeftTstartG['Group'] = "mtLeft""
